import Head from "next/head";
import HeroSection from "@/components/HeroSection";
import PromoSection from "@/components/PromoSection";
import NewArrival from "@/components/NewArrival";
import ServiceInfo from "@/components/serviceInfo";
import CategoriesSection from "@/components/CategoriesSection";
import ComfortSection from "@/components/ComfortSection";
import BestSeller from "@/components/BestSeller";
import PromoBanners from "@/components/PromoBanner";
import Testimonials from "@/components/Testimonials";






export default function Home() {
  return (
    <>
      <Head>
        <title>Home Decor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <HeroSection />

      <PromoSection />

      <NewArrival />

      <ServiceInfo />

      <CategoriesSection />

      <ComfortSection />

      <BestSeller />

      <PromoBanners />

      <Testimonials />

   

      
    </>
  );
}
